class ModelProjectInfo {
  String message;
  bool success;
  int code;
  DataBean data;

  ModelProjectInfo({this.message, this.success, this.code, this.data});

  ModelProjectInfo.fromJson(Map<String, dynamic> json) {    
    this.message = json['message'];
    this.success = json['success'];
    this.code = json['code'];
    this.data = json['data'] != null ? DataBean.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['message'] = this.message;
    data['success'] = this.success;
    data['code'] = this.code;
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    return data;
  }

}

class DataBean {
  var tenantId;
  var createEmpId;
  var createEmpName;
  var createDeptId;
  var createDeptName;
  var modifyDate;
  var modifyEmpId;
  var modifyEmpName;
  var deleteDate;
  var deleteEmpId;
  var deleteEmpName;
  var projId;
  var projNo;
  var itemName;
  var mainProjName;
  var projName;
  var projLeaderId;
  var projLeaderDepId;
  var projTypeId;
  var projDepId;
  var projRegister;
  var projAreaId;
  var projNote;
  var projArchTempId;
  var projArchTempPreId;
  var custCompName;
  var custCompId;
  var custLinkId;
  var custLinkName;
  var custLinkSex;
  var custLinkTel;
  var custLinkEmail;
  var custDuty;
  var selfTaskType;
  var selfTaskShape;
  var selfTaskUrgent;
  var selfTaskGist;
  var selfTaskGistNo;
  var selfTaskSource;
  var selfTaskContent;
  var selfTaskCapitalSource;
  var selfTaskLeadContent;
  var selfTaskOthers;
  var projAffix;
  var projJoinDepIds;
  var parentId;
  var voltageLevel;
  var projLeaderName;
  var projTypeName;
  var stageList;
  var stageId;
  var stageName;
  var leaderName;
  var planStartTime;
  var planEndTime;
  var planStartDate;
  var planEndDate;
  var realName;
  var projCount;
  var startFlow;
  var flowStatus;
  var status;
  var son;
  bool deleteMark;
  bool hasSubProj;
  int type;
  num createDate;
  num projRegisterDate;
  num projApproval;
  num projPlanStartDate;
  num projPlanFinishDate;
  num selfTaskLeadDate;
  List<FilesListBean> files;

  DataBean({this.tenantId, this.createEmpId, this.createEmpName, this.createDeptId, this.createDeptName, this.modifyDate, this.modifyEmpId, this.modifyEmpName, this.deleteDate, this.deleteEmpId, this.deleteEmpName, this.projId, this.projNo, this.itemName, this.mainProjName, this.projName, this.projLeaderId, this.projLeaderDepId, this.projTypeId, this.projDepId, this.projRegister, this.projAreaId, this.projNote, this.projArchTempId, this.projArchTempPreId, this.custCompName, this.custCompId, this.custLinkId, this.custLinkName, this.custLinkSex, this.custLinkTel, this.custLinkEmail, this.custDuty, this.selfTaskType, this.selfTaskShape, this.selfTaskUrgent, this.selfTaskGist, this.selfTaskGistNo, this.selfTaskSource, this.selfTaskContent, this.selfTaskCapitalSource, this.selfTaskLeadContent, this.selfTaskOthers, this.projAffix, this.projJoinDepIds, this.parentId, this.voltageLevel, this.projLeaderName, this.projTypeName, this.stageList, this.stageId, this.stageName, this.leaderName, this.planStartTime, this.planEndTime, this.planStartDate, this.planEndDate, this.realName, this.projCount, this.startFlow, this.flowStatus, this.status, this.son, this.deleteMark, this.hasSubProj, this.type, this.createDate, this.projRegisterDate, this.projApproval, this.projPlanStartDate, this.projPlanFinishDate, this.selfTaskLeadDate, this.files});

  DataBean.fromJson(Map<String, dynamic> json) {    
    this.tenantId = json['tenantId'];
    this.createEmpId = json['createEmpId'];
    this.createEmpName = json['createEmpName'];
    this.createDeptId = json['createDeptId'];
    this.createDeptName = json['createDeptName'];
    this.modifyDate = json['modifyDate'];
    this.modifyEmpId = json['modifyEmpId'];
    this.modifyEmpName = json['modifyEmpName'];
    this.deleteDate = json['deleteDate'];
    this.deleteEmpId = json['deleteEmpId'];
    this.deleteEmpName = json['deleteEmpName'];
    this.projId = json['projId'];
    this.projNo = json['projNo'];
    this.itemName = json['itemName'];
    this.mainProjName = json['mainProjName'];
    this.projName = json['projName'];
    this.projLeaderId = json['projLeaderId'];
    this.projLeaderDepId = json['projLeaderDepId'];
    this.projTypeId = json['projTypeId'];
    this.projDepId = json['projDepId'];
    this.projRegister = json['projRegister'];
    this.projAreaId = json['projAreaId'];
    this.projNote = json['projNote'];
    this.projArchTempId = json['projArchTempId'];
    this.projArchTempPreId = json['projArchTempPreId'];
    this.custCompName = json['custCompName'];
    this.custCompId = json['custCompId'];
    this.custLinkId = json['custLinkId'];
    this.custLinkName = json['custLinkName'];
    this.custLinkSex = json['custLinkSex'];
    this.custLinkTel = json['custLinkTel'];
    this.custLinkEmail = json['custLinkEmail'];
    this.custDuty = json['custDuty'];
    this.selfTaskType = json['selfTaskType'];
    this.selfTaskShape = json['selfTaskShape'];
    this.selfTaskUrgent = json['selfTaskUrgent'];
    this.selfTaskGist = json['selfTaskGist'];
    this.selfTaskGistNo = json['selfTaskGistNo'];
    this.selfTaskSource = json['selfTaskSource'];
    this.selfTaskContent = json['selfTaskContent'];
    this.selfTaskCapitalSource = json['selfTaskCapitalSource'];
    this.selfTaskLeadContent = json['selfTaskLeadContent'];
    this.selfTaskOthers = json['selfTaskOthers'];
    this.projAffix = json['projAffix'];
    this.projJoinDepIds = json['projJoinDepIds'];
    this.parentId = json['parentId'];
    this.voltageLevel = json['voltageLevel'];
    this.projLeaderName = json['projLeaderName'];
    this.projTypeName = json['projTypeName'];
    this.stageList = json['stageList'];
    this.stageId = json['stageId'];
    this.stageName = json['stageName'];
    this.leaderName = json['leaderName'];
    this.planStartTime = json['planStartTime'];
    this.planEndTime = json['planEndTime'];
    this.planStartDate = json['planStartDate'];
    this.planEndDate = json['planEndDate'];
    this.realName = json['realName'];
    this.projCount = json['projCount'];
    this.startFlow = json['startFlow'];
    this.flowStatus = json['flowStatus'];
    this.status = json['status'];
    this.son = json['son'];
    this.deleteMark = json['deleteMark'];
    this.hasSubProj = json['hasSubProj'];
    this.type = json['type'];
    this.createDate = json['createDate'];
    this.projRegisterDate = json['projRegisterDate'];
    this.projApproval = json['projApproval'];
    this.projPlanStartDate = json['projPlanStartDate'];
    this.projPlanFinishDate = json['projPlanFinishDate'];
    this.selfTaskLeadDate = json['selfTaskLeadDate'];
    this.files = (json['files'] as List)!=null?(json['files'] as List).map((i) => FilesListBean.fromJson(i)).toList():null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['tenantId'] = this.tenantId;
    data['createEmpId'] = this.createEmpId;
    data['createEmpName'] = this.createEmpName;
    data['createDeptId'] = this.createDeptId;
    data['createDeptName'] = this.createDeptName;
    data['modifyDate'] = this.modifyDate;
    data['modifyEmpId'] = this.modifyEmpId;
    data['modifyEmpName'] = this.modifyEmpName;
    data['deleteDate'] = this.deleteDate;
    data['deleteEmpId'] = this.deleteEmpId;
    data['deleteEmpName'] = this.deleteEmpName;
    data['projId'] = this.projId;
    data['projNo'] = this.projNo;
    data['itemName'] = this.itemName;
    data['mainProjName'] = this.mainProjName;
    data['projName'] = this.projName;
    data['projLeaderId'] = this.projLeaderId;
    data['projLeaderDepId'] = this.projLeaderDepId;
    data['projTypeId'] = this.projTypeId;
    data['projDepId'] = this.projDepId;
    data['projRegister'] = this.projRegister;
    data['projAreaId'] = this.projAreaId;
    data['projNote'] = this.projNote;
    data['projArchTempId'] = this.projArchTempId;
    data['projArchTempPreId'] = this.projArchTempPreId;
    data['custCompName'] = this.custCompName;
    data['custCompId'] = this.custCompId;
    data['custLinkId'] = this.custLinkId;
    data['custLinkName'] = this.custLinkName;
    data['custLinkSex'] = this.custLinkSex;
    data['custLinkTel'] = this.custLinkTel;
    data['custLinkEmail'] = this.custLinkEmail;
    data['custDuty'] = this.custDuty;
    data['selfTaskType'] = this.selfTaskType;
    data['selfTaskShape'] = this.selfTaskShape;
    data['selfTaskUrgent'] = this.selfTaskUrgent;
    data['selfTaskGist'] = this.selfTaskGist;
    data['selfTaskGistNo'] = this.selfTaskGistNo;
    data['selfTaskSource'] = this.selfTaskSource;
    data['selfTaskContent'] = this.selfTaskContent;
    data['selfTaskCapitalSource'] = this.selfTaskCapitalSource;
    data['selfTaskLeadContent'] = this.selfTaskLeadContent;
    data['selfTaskOthers'] = this.selfTaskOthers;
    data['projAffix'] = this.projAffix;
    data['projJoinDepIds'] = this.projJoinDepIds;
    data['parentId'] = this.parentId;
    data['voltageLevel'] = this.voltageLevel;
    data['projLeaderName'] = this.projLeaderName;
    data['projTypeName'] = this.projTypeName;
    data['stageList'] = this.stageList;
    data['stageId'] = this.stageId;
    data['stageName'] = this.stageName;
    data['leaderName'] = this.leaderName;
    data['planStartTime'] = this.planStartTime;
    data['planEndTime'] = this.planEndTime;
    data['planStartDate'] = this.planStartDate;
    data['planEndDate'] = this.planEndDate;
    data['realName'] = this.realName;
    data['projCount'] = this.projCount;
    data['startFlow'] = this.startFlow;
    data['flowStatus'] = this.flowStatus;
    data['status'] = this.status;
    data['son'] = this.son;
    data['deleteMark'] = this.deleteMark;
    data['hasSubProj'] = this.hasSubProj;
    data['type'] = this.type;
    data['createDate'] = this.createDate;
    data['projRegisterDate'] = this.projRegisterDate;
    data['projApproval'] = this.projApproval;
    data['projPlanStartDate'] = this.projPlanStartDate;
    data['projPlanFinishDate'] = this.projPlanFinishDate;
    data['selfTaskLeadDate'] = this.selfTaskLeadDate;
    data['files'] = this.files != null?this.files.map((i) => i.toJson()).toList():null;
    return data;
  }
}

class FilesListBean {
  String tenantId;
  String createEmpId;
  String createEmpName;
  String createDeptId;
  String createDeptName;
  String modifyDate;
  String modifyEmpId;
  String modifyEmpName;
  String deleteDate;
  String deleteEmpId;
  String deleteEmpName;
  String attachId;
  String fileId;
  String filePath;
  String fileType;
  String fileName;
  String bizId;
  String projId;
  bool deleteMark;
  int fileSize;
  int fileVersion;
  int nodeType;
  int type;
  num createDate;
  num lastModifiedDate;

  FilesListBean({this.tenantId, this.createEmpId, this.createEmpName, this.createDeptId, this.createDeptName, this.modifyDate, this.modifyEmpId, this.modifyEmpName, this.deleteDate, this.deleteEmpId, this.deleteEmpName, this.attachId, this.fileId, this.filePath, this.fileType, this.fileName, this.bizId, this.projId, this.deleteMark, this.fileSize, this.fileVersion, this.nodeType, this.type, this.createDate, this.lastModifiedDate});

  FilesListBean.fromJson(Map<String, dynamic> json) {    
    this.tenantId = json['tenantId'];
    this.createEmpId = json['createEmpId'];
    this.createEmpName = json['createEmpName'];
    this.createDeptId = json['createDeptId'];
    this.createDeptName = json['createDeptName'];
    this.modifyDate = json['modifyDate'];
    this.modifyEmpId = json['modifyEmpId'];
    this.modifyEmpName = json['modifyEmpName'];
    this.deleteDate = json['deleteDate'];
    this.deleteEmpId = json['deleteEmpId'];
    this.deleteEmpName = json['deleteEmpName'];
    this.attachId = json['attachId'];
    this.fileId = json['fileId'];
    this.filePath = json['filePath'];
    this.fileType = json['fileType'];
    this.fileName = json['fileName'];
    this.bizId = json['bizId'];
    this.projId = json['projId'];
    this.deleteMark = json['deleteMark'];
    this.fileSize = json['fileSize'];
    this.fileVersion = json['fileVersion'];
    this.nodeType = json['nodeType'];
    this.type = json['type'];
    this.createDate = json['createDate'];
    this.lastModifiedDate = json['lastModifiedDate'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['tenantId'] = this.tenantId;
    data['createEmpId'] = this.createEmpId;
    data['createEmpName'] = this.createEmpName;
    data['createDeptId'] = this.createDeptId;
    data['createDeptName'] = this.createDeptName;
    data['modifyDate'] = this.modifyDate;
    data['modifyEmpId'] = this.modifyEmpId;
    data['modifyEmpName'] = this.modifyEmpName;
    data['deleteDate'] = this.deleteDate;
    data['deleteEmpId'] = this.deleteEmpId;
    data['deleteEmpName'] = this.deleteEmpName;
    data['attachId'] = this.attachId;
    data['fileId'] = this.fileId;
    data['filePath'] = this.filePath;
    data['fileType'] = this.fileType;
    data['fileName'] = this.fileName;
    data['bizId'] = this.bizId;
    data['projId'] = this.projId;
    data['deleteMark'] = this.deleteMark;
    data['fileSize'] = this.fileSize;
    data['fileVersion'] = this.fileVersion;
    data['nodeType'] = this.nodeType;
    data['type'] = this.type;
    data['createDate'] = this.createDate;
    data['lastModifiedDate'] = this.lastModifiedDate;
    return data;
  }
}
